import { StyleSheet } from 'react-native';
export const colors = {
  bg: '#101411',
  panel: '#191f1a',
  line: '#303a31',
  text: '#edf1e8',
  muted: '#98a593',
  green: '#d1f59b',
};
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    paddingHorizontal: 36,
    paddingVertical: 24,
    borderBottomWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 16,
  },
  brand: { flexDirection: 'row', gap: 14, alignItems: 'center' },
  mark: {
    backgroundColor: colors.green,
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  markText: { fontSize: 28, fontWeight: '800', color: colors.bg },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -1,
  },
  subtitle: { fontSize: 12, color: colors.muted, marginTop: 4 },
  pill: {
    fontSize: 10,
    letterSpacing: 1.5,
    borderWidth: 1,
    borderColor: colors.line,
    padding: 10,
    borderRadius: 20,
  },
  page: { padding: 32, maxWidth: 1600, width: '100%', alignSelf: 'center' },
  projectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginBottom: 30,
  },
  eyebrow: {
    color: colors.green,
    fontSize: 10,
    letterSpacing: 2,
    marginBottom: 10,
  },
  projectName: {
    color: colors.text,
    fontSize: 30,
    fontWeight: '600',
    letterSpacing: -1,
  },
  path: { color: colors.muted, fontSize: 12, marginTop: 8 },
  meta: { color: colors.muted, fontSize: 11 },
  columns: { flexDirection: 'row', gap: 22, alignItems: 'stretch' },
  sidebar: { width: 370, gap: 20 },
  card: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    padding: 22,
    gap: 14,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  heading: { color: colors.text, fontWeight: '600', fontSize: 16 },
  status: { color: colors.green, fontSize: 9, letterSpacing: 1 },
  description: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  button: {
    borderWidth: 1,
    borderColor: '#465140',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  primary: { backgroundColor: colors.green, borderColor: colors.green },
  buttonText: { color: colors.text, fontSize: 12, fontWeight: '600' },
  hint: { color: colors.muted, fontSize: 11, lineHeight: 18 },
  device: {
    borderTopWidth: 1,
    borderColor: colors.line,
    paddingTop: 16,
    gap: 9,
  },
  deviceName: { color: colors.text, fontSize: 13, flex: 1 },
  platform: { color: colors.muted, fontSize: 9 },
  warning: { color: '#dcb388', fontSize: 11, lineHeight: 18 },
  console: {
    flex: 1,
    minWidth: 0,
    backgroundColor: '#0b0e0c',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 16,
    overflow: 'hidden',
    minHeight: 540,
    maxHeight: 780,
  },
  consoleHeader: {
    padding: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: colors.line,
  },
  tabs: { flexGrow: 0, maxHeight: 66 },
  tab: { padding: 10, borderRadius: 6, backgroundColor: colors.panel },
  tabSelected: { backgroundColor: '#34422c' },
  tabText: { color: colors.text, fontSize: 11 },
  log: { flex: 1, padding: 22 },
  logText: {
    color: '#c5d3be',
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 21,
  },
  consoleFooter: {
    padding: 16,
    borderTopWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  error: {
    backgroundColor: '#422a25',
    color: '#ffcfba',
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  footer: { color: '#65725f', fontSize: 9, letterSpacing: 2, marginTop: 28 },
});
